name: ENV Variables
on: [push]
env:
  wf_env: Available to all jobs
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available in all steps in log-env job
    steps:
      - name: Log env Variables
        env:
          STEP_ENV: Available to only this step
        run: |
          echo "wf_env: ${wf_env}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: Log ENV 2
        run: |
          echo "wf_env: ${wf_env}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps: 
      - name: Default ENV Variables
        run: | 
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_REPOSITORY ${GITHUB_REPOSITORY}"
          echo "wf_env: ${wf_env}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
