name: Shell Comands
on: [push]
jobs:
  run-shell-comand:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello Worlds"
      - name: multiline command
        run: |
          node -v
          npm -v
      - name: python comand
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windowd-command:
    needs: [run-shell-comand]
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash

      
      